# Practice file 

In [89]:
import numpy as np 
a = np.array([1,2,3,4])
print(type(a))
a.shape

<class 'numpy.ndarray'>


(4,)

In [90]:
b = np.array([[1,2,3,4], [4,5,6,7]])
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [91]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

In [92]:
b.shape

(2, 4)

In [93]:
np.dot(b, b.T)

array([[ 30,  60],
       [ 60, 126]])

In [94]:
matrix = np.array([])
np.random.randint?


Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 

In [95]:
matrix = np.random.randint(1,100,(5,5))
matrix

array([[53, 15, 68, 73,  3],
       [31,  1, 40, 38, 42],
       [54, 19, 76,  4, 62],
       [57, 11, 91,  3, 54],
       [37, 69, 65, 93, 30]])

In [96]:
print(np.max(matrix))
print(np.min(matrix))
print(np.argmin(matrix))
print(np.argmax(matrix))

np.unique(matrix)



93
1
6
23


array([ 1,  3,  4, 11, 15, 19, 30, 31, 37, 38, 40, 42, 53, 54, 57, 62, 65,
       68, 69, 73, 76, 91, 93])

In [97]:
a = np.array([1,1,1,2,2,2,2,2,3,3,3,4,4,4,4,4,4])
np.unique(a)
matrix = np.unique(a, return_counts = True)

In [98]:
matrix

(array([1, 2, 3, 4]), array([3, 5, 3, 6], dtype=int64))

In [99]:
matrix[0][np.argmax(matrix[1])]

4

In [100]:
matrix

(array([1, 2, 3, 4]), array([3, 5, 3, 6], dtype=int64))

In [101]:
matrix[2:4, 1:4]

TypeError: tuple indices must be integers or slices, not tuple

# Data visualization

In [ ]:
import matplotlib.pyplot as plt 
x = np.array([1,2,3,4,5])
y = x**2 + 3
print(x,y)

In [ ]:
plt.plot(x, y)
plt.show()
plt.style.available
plt.style.use('seaborn')
plt.title("My Seaborn Graph")
plt.plot(x, y, label = "Stock")
plt.legend()
plt.xlabel("stock price")
plt.ylabel("time")

In [ ]:
plt.style.use('seaborn')
plt.title("My Seaborn Graph")
plt.plot(x, y, label = "Stock")
plt.plot(x, x**2, label = "StockPrice")
plt.legend()
plt.xlabel("stock price")
plt.ylabel("time")

In [ ]:
import cv2

In [ ]:
img = cv2.imread('lovepic.jpg')
print(img.shape)
plt.axis('off')
plt.imshow(img)

In [ ]:
rgb_image = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(rgb_image)
# plt.axis('off')
# plt.show(rgb_image)
croppedImage = rgb_image()

In [ ]:
croppedImage = rgb_image[200:800, 650:1200, :]
plt.axis('off')
plt.title("Cropped Image")
plt.imshow(croppedImage)


In [ ]:
img = cv2.resize(img, (100,100))

In [ ]:
plt.imshow(img)

In [ ]:
img.shape

# Pandas : Data Visualization

In [ ]:
import pandas as pd

In [ ]:
pokemon = {
    "Pokemon_Height" : np.random.randint(10, 400, 5),
    "Pokemon_Weight" : np.random.randint(200, 500, 5),
    "Pokemon_Power" : np.random.randint(1000, 4000, 5),
}
pokemon

In [ ]:
df = pd.DataFrame(pokemon)
df

In [ ]:
# df.head(n = 2)
print(df)
print(df.head)
df.to_csv('Pokemon_data.csv')

In [ ]:
df.to_csv('Poki.csv', index = False)

In [ ]:
df.drop(columns=[
    'bound method NDFrame.head of'
])

In [ ]:
df.head()